--test import
--INSERT INTO USER_AUTH (ID,NAME, PASSWORD, ENABLED) VALUES (1,'user', '$2y$12$cVVgu6vzuAUQT7zfhMcuq.3UpkmY/I4gA4RcxqE5.7v8X.SUYBbNu', true);
--INSERT INTO USER_AUTH (ID,NAME, PASSWORD, ENABLED) VALUES (2,'admin', '$2y$12$NLpTn2.MQPKO52GTz3erJOpCQPSUhBC4G8RRrgKT77onOvBbjOnTK', true);
--INSERT INTO USER_AUTH (ID,NAME, PASSWORD, ENABLED) VALUES (3,'diego', '$2y$12$jNR.5yiTe1Zf0GaMeLhzmeQIMAOt6/WtHUkcf93./tIPM5ImdaoWW', true);
--INSERT INTO USER_AUTH_ROLES (ID,USER_ID,ROLE_ID) VALUES (3,1, 1);


