--test import
INSERT INTO USER_SECURITY (USER_ID,NAME, PASSWORD, ENABLED, ROLE) VALUES (1,'user', '$2y$12$cVVgu6vzuAUQT7zfhMcuq.3UpkmY/I4gA4RcxqE5.7v8X.SUYBbNu', true,'USER');
INSERT INTO USER_SECURITY (USER_ID,NAME, PASSWORD, ENABLED, ROLE) VALUES (2,'admin', '$2y$12$NLpTn2.MQPKO52GTz3erJOpCQPSUhBC4G8RRrgKT77onOvBbjOnTK', true,'ADMIN');
INSERT INTO USER_SECURITY (USER_ID,NAME, PASSWORD, ENABLED, ROLE) VALUES (3,'diego', '$2y$12$jNR.5yiTe1Zf0GaMeLhzmeQIMAOt6/WtHUkcf93./tIPM5ImdaoWW', true,'USER');
